spring:
  application:
    name: my-calendar-backend
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/my_calendar
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: calendar
    out-of-order: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_CALENDAR_EMAIL}
    password: ${MY_CALENDAR_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
logging:
  level:
    org.springframework.security: TRACE
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 900000 # 15 minutes
      refresh-token:
        expiration: 604800000 # 7 days