spring:
  application:
    name: my-calendar-backend
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/my_calendar
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: calendar
